libmapnik-jni.jnilib: mapnikjni.cpp mapnikjni.h
	g++ -dynamiclib -o libmapnik-jni.jnilib \
		-I/usr/X11/include \
		-I/usr/X11/include/freetype2 \
		-I/System/Library/Frameworks/JavaVM.framework/Headers \
		mapnikjni.cpp \
		-lmapnik2 -framework JavaVM
	
clean:
	rm libmapnik-jni.jnilib
	
