include common.mk

libmapnik-jni.jnilib: $(SOURCE_DEPENDS)
	$(CXX) -dynamiclib -o libmapnik-jni.jnilib \
		$(CFLAGS) \
		$(MAPNIK_CFLAGS) \
		$(JAVA_CFLAGS) \
		mapnikjni.cpp \
		$(LDFLAGS) \
		$(MAPNIK_LIBS) -framework JavaVM
	
clean:
	rm libmapnik-jni.jnilib
	

