include common.mk

JAVA_CMD ?= java
CFLAGS ?= -O3
FREETYPE_CFLAGS ?= $(shell freetype-config --cflags)
JAVA_CFLAGS ?= $(shell $(JAVA_CMD) -jar java-config.jar --cflags)


libmapnik-jni.jnilib: mapnikjni.cpp mapnikjni.h
	g++ -dynamiclib -o libmapnik-jni.jnilib \
		$(CFLAGS) \
		$(FREETYPE_CFLAGS) \
		$(JAVA_CFLAGS) \
		mapnikjni.cpp \
		$(LDFLAGS) \
		-lmapnik2 -framework JavaVM
	
clean:
	rm libmapnik-jni.jnilib
	

