include common.mk


libmapnik-jni.so: $(SOURCE_DEPENDS)
	$(CXX) -o libmapnik-jni.so \
		-fPIC -shared \
		$(CFLAGS) \
		$(MAPNIK_CFLAGS) \
		$(JAVA_CFLAGS) \
		mapnikjni.cpp \
		$(LDFLAGS) \
		$(MAPNIK_LIBS)
	
clean:
	rm libmapnik-jni.so
	
